#!/usr/bin/env python3
"""Generate CATALOG.md from the frontmatter of every skill under ./skills.

Run after syncing skills so the catalog matches the repository contents.
The output file is generated - do not edit it by hand.
"""
import pathlib
import re
import sys
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
OUT = ROOT / "CATALOG.md"


def split_frontmatter(text):
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            return "\n".join(lines[1:i])
    return None


def get_field(fm, key):
    lines = fm.split("\n")
    for i, ln in enumerate(lines):
        m = re.match(r"^([A-Za-z_][\w\-]*):\s*(.*)$", ln)
        if m and m.group(1) == key:
            val = m.group(2).strip()
            if val in (">", "|", ">-", "|-", ">+", "|+"):
                buf = []
                for j in range(i + 1, len(lines)):
                    nxt = lines[j]
                    if nxt.strip() == "":
                        buf.append("")
                        continue
                    if nxt[:1].isspace():
                        buf.append(nxt.strip())
                    else:
                        break
                return " ".join(x for x in buf if x).strip()
            return val.strip("\"'")
    return None


def nested_field(fm, key):
    for ln in fm.split("\n"):
        m = re.match(r"^\s+([A-Za-z_][\w\-]*):\s*(.*)$", ln)
        if m and m.group(1) == key:
            return m.group(2).strip().strip("\"'")
    return None


def short(desc, limit=150):
    desc = re.sub(r"\s+", " ", desc or "").strip()
    if len(desc) <= limit:
        return desc
    cut = desc[:limit]
    return cut[: cut.rfind(" ")] + " ..." if " " in cut else cut + " ..."


def main():
    rows = []
    for d in sorted(p for p in SKILLS_DIR.iterdir() if p.is_dir()):
        skill_md = d / "SKILL.md"
        if not skill_md.is_file():
            continue
        fm = split_frontmatter(skill_md.read_text(encoding="utf-8", errors="replace"))
        if fm is None:
            continue
        rows.append({
            "name": get_field(fm, "name") or d.name,
            "dir": d.name,
            "desc": short(get_field(fm, "description")),
            "version": nested_field(fm, "version") or get_field(fm, "version") or "-",
            "status": nested_field(fm, "status") or "-",
            "files": sum(1 for p in d.rglob("*") if p.is_file()),
        })

    lines = [
        "# Catalog",
        "",
        "> Auto-generated by `scripts/build-catalog.py` - do not edit by hand.",
        "> Generated on %s." % date.today().isoformat(),
        "",
        "| Skill | Description | Version | Status | Files |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append("| [`%s`](skills/%s/) | %s | %s | %s | %d |"
                     % (r["name"], r["dir"], r["desc"].replace("|", "\\|"),
                        r["version"], r["status"], r["files"]))
    lines.append("")
    lines.append("Total: **%d** skill(s)." % len(rows))
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print("Wrote %s (%d skill(s))" % (OUT, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
